name: thbck/page-header
typeName: thbck_pageheader
group: slcreation
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  -
    identifier: subheader
    type: Text
  -
    identifier: bodytext
    useExistingField: true
    enableRichtext: true
  -
    identifier: image
    type: Image
    useExistingField: true